### ISSUE TITLE
crontab is missing

### ISSUE THREAD

**Issue by christianprim** [ViViDboarder/docker-duplicity-cron#5]
vividboarder/docker-duplicity-cron has no crontab.

Test: docker exec -it container-name bash
In container enter: crontab

So no cron job running.

**Comment by ViViDboarder** [comment]
Hmm, looks like `ubuntu:xenial` does not include `cron`. I've been running the Raspbian version, which is unaffected as `Dockerfile.raspbian` already intalls `cron`. Added a new test, verified that the test catches the failure you're seeing, and then added the fix.

Should be good to go as soon as the images finish building.

Thanks for reporting!
